### ISSUE TITLE
Base table or view not found

### ISSUE THREAD

**Issue by 1415926535** [DevMarketer/DevMarketer#12]
> (2/2) QueryException
> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'devmarketer.role' doesn't exist (SQL: select count(*) as aggregate from `role` where `name` = asdf)

> (1/2) PDOException
> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'devmarketer.role' doesn't exist

I was getting this on my 'follow along' code base and couldn't figure it out. So I downloaded your code from here and ran `composer install` and then `npm install` and then sshed into Homestead to run `artisan migrate --seed`.  Same error. 

Since I can add new users with no problem, I compared UserController and RoleController line by line looking for "role" where "roles" should be and didn't see anything. But in the error it's clearly looking for the table "role" not "roles". 

I didn't run any of the Laratrust commands on your code base during installation. Is that the root of this? I've done a bunch of googling  using laratrust and just laravel to find a clue and didn't see anything similar. 

Where is Laravel getting confused and looking for the table role instead of roles? 
If this isn't something you know off the top of your head, close this issue out and I'll figure it out eventually. 
![2017-08-14-150908_835x1000_scrot](https://user-images.githubusercontent.com/15851161/29287268-e2246b9e-8102-11e7-98e9-eac004590e5b.png)
![2017-08-14-150941_874x1057_scrot](https://user-images.githubusercontent.com/15851161/29287269-e224ceae-8102-11e7-999a-ea7e9aae8774.png)

**Comment by wehjey** [comment]
You can always specify the table your model would use. See below:
protected $table = 'table_name';

**Comment by true2thepen** [comment]
The folllowing line in RoleController.php:
'name' => 'required|max:100|alpha_dash|unique:role,name',

should be:
'name' => 'required|max:100|alpha_dash|unique:roles,name',

**Comment by bantawa04** [comment]
I also encountered same error . @wehjey adding that snippet isn't helping at all.

**Comment by jacurtis** [comment]
It appears based on the original error from @1415926535 that you do not have a table in your database for the laratrust tables.

After you run `composer install` make sure that you follow the installation steps for LaraTrust here: http://laratrust.readthedocs.io/en/4.0/installation.html

Also check your database to make sure you have those tables setup and everything is configured correctly.

**Comment by jacurtis** [comment]
haven't heard anything new on this in 5 days. I think this is a problem with not configuring Laratrust correctly to get the roles tables in your database before seeding it.

I am closing the issue. If @1415926535 continues to have problems, you can re-open the issue.

**Comment by bantawa04** [comment]
I'm still facing error on issue. There is `roles` table in the DB and `roles` is filled with `pa db:seed`. The above mentioned error is encountered when I want to create new role. I tried by specifying table name explicitly in model. Bu it didn't worked out.  FYI: this issue is on cloned version of the project.

**Comment by jacurtis** [comment]
Which version of LaraTrust are you all using? I was just informed that there is now a version 5 and this site is currently using version 4. I am not sure if that is the same problem or not.

Also based on the error I see posted at the top of this issue, it looks like it is looking for `devmarketer.role` which means it is looking for a table called _"role"_ in the _"devmarketer"_ database.

This should be _"roles"_. I am not sure what is causing the issue since I can not duplicate it, but maybe that can help identify the issue.

**Comment by carusogabriel** [comment]
This bug has been solved with #21

**Comment by jacurtis** [comment]
Oh that makes sense. Thanks for mentioning that @gabriel-caruso. That is the problem!

So everyone knows, there was a typo in my validation that checked the "role" database instead of the "roles" database for a unique record. That is why this error occurred, because when you saved a new user (in the process of migrating) it would attempt to validate against the "role" table which doesnt exist.

This should be fixed now as I have accepted a PR from @gabriel-caruso which resolves this. You can read #21 and view code 99ed4f8 to see details.

To fix: run a `git pull` in your terminal to get the newest changes and then try everything again with the updated code.
