### ISSUE TITLE
Regarding processing videos

### ISSUE THREAD

**Issue by roni-estein** [DevMarketer/DevMarketer#15]
Hi Alex, have you considered asking the community for some assistance? I’m a big fan of the tooling aspect of the videos. Details that we all run into eventually, like the mixing preprocessors issue, or combining multiple vue elements on one page and different ones on another. Things that you run into when you know he basics but are getting up to speed in a new technology stack. Or branching out past a post and comment app.

Those inconsequentials covered in these “watch me work videos” that are the main reason that I (and most intermediate users) enjoy them. We aren’t there for the what’s new in laravel, but for he multiauth series. I’d kill for a series on shared models between code sets, where you could some models, controllers migrations and factories between multiple apps. Extracting them to packages. That would be killer. But I’m getting off topic. I would gladly contribute 3 hours a week in one way or another to help these videos keep coming. I’m sure many people on here would too.

Just something to consider.
- cheers

**Comment by jacurtis** [comment]
Thanks for the feedback. I have been hearing several things from other people that feel similar. I am trying to figure out how to make all of this happen. As for right now I intend to cover more details than initially anticipated. I will be publishing more content that is not part of the large series in order to make people that don't want the "watch me work" content and then try to publish these as well. That way there is a variety of content on the channel.

**Comment by jacurtis** [comment]
I am going to close this. Feel free to open it if you have any further comment.
