### ISSUE TITLE
HttpException No message

### ISSUE THREAD

**Issue by bantawa04** [DevMarketer/DevMarketer#16]
While trying to access url `http://localhost:8000/manage/dashboard` directly without logging in we are getting `HttpException No message` error. Tried to fix it by my own following the tutorials of multi-auth series and try to redirect it to login but I found too many things flying around.  **unauthenticated.** method isn't available in `Kernel.php` in Laravel 5.5

**Comment by jacurtis** [comment]
Ok, i will look into it and see if i can replicate the problem. Yes the unauthenticated method isnt in Kernal anymore which is causing all sorts of problems for my multi-auth series.

**Comment by jacurtis** [comment]
This is actually the intended function. You can adjust how LaraTrust handles an unauthorized user by going to `config/laratrust.php` and at the bottom there are settings for how the middleware handles exceptions.

![image](https://user-images.githubusercontent.com/537329/31590588-0172b7be-b1d0-11e7-92d4-fcc67777c3d0.png)

I had it set to abort because I didnt want to let unauthorized users know that this was a valid URL. However, depending on your use case, a redirect might be more appropriate and you can change it here. I changed it to the redirect method and was redirect instead of getting the HTTP error.

I actually want the HTTP error so I am going to move it back to abort, because as I stated I do not want to let unauthorized users know that this is a valid URL.
