### ISSUE TITLE
[Proposal] Refactoring controllers

### ISSUE THREAD

**Issue by carusogabriel** [DevMarketer/DevMarketer#4]
Alex, I'm considering to refactor some controllers, but I don't know your opinion about, so let me ask you:

### Redirecting With Flashed Session Data
Instead of import the `Session` facade, call the `flash`method, why we just don't use the [`with`](https://laravel.com/docs/master/responses#redirecting-with-flashed-session-data)?

### Request validation
A small one, but works like a charm: [`validateWith`](https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Validation/ValidatesRequests.php#L18) method, that avoid to pass the request variable. Ex:
```php 
$this->validate($request, $array_of_rules)
```
becomes
```php 
$this->validateWith($array_of_rules)
```

### Model creation
I know you like to instantiate a new Model then set the attributes explicitly, but, [Mass Assignment](https://laravel.com/docs/5.4/eloquent#mass-assignment) it's beautiful. Take a look at how the current `store` method in the `RoleController` can become:
```php
$role = Role::create(request(['display_name', 'name', 'description]));
```

I'm intent to apply this changes at `Role`, `Permission` and `User` controllers. What do you think?

:smile:

**Comment by jacurtis** [comment]
I was unfamiliar with the `$this->validateWith()` method. I did not know it existed which is the simple reason i have not used it. I will probably incorporate that soon. It is a nice little shortcut. It always felt dumb manually adding the `$request` into it since that is what you are validating 99% of the time.

I get asked about Mass assignment a lot. The reason I don't use it is simple. Because I teach this stuff so much (both online and locally) i generally avoid teaching newcomers about mass assignment. Newcomers don't do well with "magic" methods that do a lot of hidden work behind the scenes. So showing them manually setting them is good so they can see how it works. There are also times when you really don't want to do mass assignment (or you need to put in some more complex work to make it work) such as when you are filling in non-mass-assignable fields. So i have moved away from teaching mass assignment to beginners, because it is a major point of confusion for them and makes teaching something like saving a new record in the database take a day instead of an hour.

Because much of my coding is teaching, and because i avoid teaching it, I have gotten out of the habit of using mass assignment even in personal projects. I don't hate mass assignment, i have nothing against it, and I agree it is far more elegant. But like I said the teaching methods I do so often get engrained as habit for me and eventually bleed over into my more personal projects. Behind the scenes mass assignment is doing the same thing I am doing manually, so it doesn't save on things like performance. Just cleanliness of the controllers.

If you wanted to work on it and submit a PR i would look it over and likely approve it. Now is a good time since we have now completed `Permission` and `Role`. We also will probably not add anything to the `User` model for another week or so. So its a good time to make those changes.

Thanks for contributing

**Comment by carusogabriel** [comment]
Hey @jacurtis!

Can I submit some refactored code (I've already submitted one (#5)), as now this project is in Laravel's 5.5 version? Or no, wait until the series end?

**Comment by jacurtis** [comment]
It is now in version 5.5. Go ahead and submit the code and ill review it.

**Comment by jacurtis** [comment]
Ive approved the changes in PR #5. Ill close this for now. Open up a new issue or pull request if you have other changes. THanks
